### ISSUE TITLE
OpenZWave 1.6 and Fibaro Motion Sensor

### ISSUE THREAD

**Issue by Locutus73** [mike182uk/homebridge-zwave#1] opened 2019-08-16 13:54 UTC
Hi, first of all thank you for your work. I want to report my experience with homebridge-zwave in my HomeKit setup (I’m a total z-wave newbie). I use an Aeotec Z-Stick Gen5 and a Fibaro Motion Sensor (the cat eye one), on my AMD64 Debain Buster ESXi virtual machine with OpenZWave 1.6. I know the prerequisites ask for 1.4, but that and 1.5 don’t have the Fibaro sensor in their database. At first I had no success with homebridge-zwave, but digging into OpenZWave Control Panel logs and into your code, with some modifications I managed to use the sensor (at least the Motion Sensor which is the one I’m interested in).
First of all I had to modify ZWave.ALARM_INDEX_HOME_SECURITY in lib/ZWave.js https://github.com/mike182uk/homebridge-zwave/blob/05388dfaa927c8d15279e8719668c7c286c50fd9/lib/ZWave.js#L256  from 10 to 7. As I already stated I’m a total z-wave noob, I’m not sure if it’s related to 1.6 or to the Fibaro, but I think it’s z-wave related, see here http://www.openzwave.com/dev/structValueID__Index__Alarm.html
After I modified that value I got some success, but the motion sensor was always triggered in HomeKit… after a fuhrer investigation I found the culprit in AccessoryManager.js here https://github.com/mike182uk/homebridge-zwave/blob/05388dfaa927c8d15279e8719668c7c286c50fd9/lib/AccessoryManager.js#L333 and here https://github.com/mike182uk/homebridge-zwave/blob/05388dfaa927c8d15279e8719668c7c286c50fd9/lib/AccessoryManager.js#L344 Basically the value returned from OpenZWave is a string and Boolean(value) always returns true. I had to modify that into value = (value=='Clear' ? false : true) (and done(null...) and now I can finally use my Fibaro Motion Sensor.

Regards.

**Comment by mike182uk** [comment] 2019-08-20 10:47
Hey @Locutus73 

Thanks for providing some feedback on this!

So yeah, as you mentioned, I think the issue is going to largely be related to using `openzwave 1.6` rather than `openzwave 1.4`. There is quite a few differences in the latest release, and at the time of authoring this plugin, the library I use to interface with `openzwave` did not support `1.6`. That may have changed since then, so i'll take a look at what would be involved in upgrading 👍 

As for casting the node value to a boolean, I'll look into that with the motion sensor I am using. I definitely don't have the same problem, but it could be possible that i have missed something.

Can you confirm the model of the device? (I'am assuming its [this](https://www.fibaro.com/en/products/motion-sensor/) one)

I believe the device also has some other sensors on it (light, temperature etc.), did you have any problems with getting those sensors to work?

**Comment by Locutus73** [comment] 2019-08-20 12:03
Yeah, the sensor is that (I live in Italy, so maybe there's a regional variant).
I didn't test light and temperature thoroughly, but IIRC they worked, I can make some further tests or grab some OpenZWave logs if you need them.
Honestly I like your plugin since it doesn't add sensors automatically and let me customize them: I don't want Siri reporting the Fibaro temperature (and I don't care about the light sensor), so I can configure it just as a motion sensor.
By the way: when I go into the HomeKit sensor details I see the make and model. but I don't see the serial number (but, who cares?) and I don't see the battery status (this would be very useful).

**Comment by mike182uk** [comment] 2019-08-31 21:46
Hey @Locutus73 

I've just published a new version of `homebridge-zwave` (`2.0.0`) which now uses `OpenZWave 1.6` and resolves the issue you reported with the motion sensor. The serial number should now also be reported for the device 🙂

If you could give this new version a go with your Fibaro sensor and let me know the outcome that would be great!

**Comment by Locutus73** [comment] 2019-09-02 09:21
Hi @mike182uk, I'm sorry, but I was very busy these days.
I hope I'll be able to test your new implementation this weekend and report back.
Thank you in advance.

Regards.

**Comment by Locutus73** [comment] 2019-09-10 16:11
Hi @mike182uk, I'm sorry for the delay.
I tested your 2.0 release quite succesfully.
Motion, temperature and light sensors seem to work.
Motion sensor isn't triggered by tampering event tho... I made a Pull Request about that.
https://github.com/mike182uk/homebridge-zwave/pull/10
I noticed two other issues (I mean, these issues were there in the old release too).
https://github.com/mike182uk/homebridge-zwave/issues/11
https://github.com/mike182uk/homebridge-zwave/issues/12

Last but not least... do you think your plugin will support this Fibaro Double Switch 2?
https://manuals.fibaro.com/switch-2/
The "Double" version should appear in HomeKit as two different switches.

Thank you in advance.
Regards.

**Comment by mike182uk** [comment] 2019-09-14 15:18
Hey @Locutus73 

Thanks for your feedback. I See you've raised GitHub issues for the things discussed in your last comment, so I'am going to close this issue for now so we can have focused discussions on the other issues 👍

**Closed by mike182uk** 2019-09-14 15:18 UTC
